export interface ProjectTemplate {
  id: string;
  title: string;
  description: string;
  technology: string;
  submissionType: string;
  learningObjective: string;
  instructions: string[];
  expectedOutput: string;
  maxMarks: number;
  difficultyLevel: string;
  estimatedTime: string;
  referenceResources: string[];
}

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  // Scratch Jr
  {
    id: "scratchjr-story",
    title: "My Animated Story",
    description: "Create a short animated story using Scratch Jr with at least 3 characters and multiple scenes. Use motion, sound, and speech blocks to bring the story to life.",
    technology: "Scratch Jr",
    submissionType: "Screenshot",
    learningObjective: "Learn to create animations, use multiple scenes, and add character interactions using Scratch Jr.",
    instructions: [
      "Open Scratch Jr and create a new project",
      "Add at least 3 characters from the character library",
      "Create at least 3 different scenes/backgrounds",
      "Add motion blocks to make characters move",
      "Add speech bubbles for character dialogues",
      "Add sound effects to your story",
      "Test your story by pressing the green flag",
      "Take screenshots of each scene"
    ],
    expectedOutput: "A complete animated story with 3+ characters, 3+ scenes, character movements, dialogues, and sound effects.",
    maxMarks: 50,
    difficultyLevel: "Easy",
    estimatedTime: "1 hour",
    referenceResources: [],
  },
  // Scratch
  {
    id: "scratch-game",
    title: "Catch the Fruit Game",
    description: "Build a simple game in Scratch where a basket moves left and right to catch falling fruits. Keep score and add a timer.",
    technology: "Scratch",
    submissionType: "Screenshot",
    learningObjective: "Learn game design concepts including sprite movement, collision detection, scoring, and timer using Scratch blocks.",
    instructions: [
      "Open Scratch and create a new project",
      "Add a basket sprite and position it at the bottom",
      "Add fruit sprites (apple, banana, orange)",
      "Program the basket to move left/right with arrow keys",
      "Program fruits to fall from random positions at the top",
      "Add collision detection — score +1 when basket catches fruit",
      "Add a score variable and display it on screen",
      "Add a 30-second timer that ends the game",
      "Add a Game Over screen showing the final score",
      "Test and debug your game"
    ],
    expectedOutput: "A working catch game with moving basket, falling fruits, score counter, timer, and game over screen.",
    maxMarks: 100,
    difficultyLevel: "Medium",
    estimatedTime: "2 hours",
    referenceResources: [],
  },
  {
    id: "scratch-quiz",
    title: "Interactive Quiz in Scratch",
    description: "Create a quiz application in Scratch with at least 5 questions, scoring, and feedback for correct/incorrect answers.",
    technology: "Scratch",
    submissionType: "Screenshot",
    learningObjective: "Learn to use variables, conditional statements, and user input in Scratch to build interactive applications.",
    instructions: [
      "Create a new Scratch project with a quiz host character",
      "Use the 'ask' block to ask at least 5 questions",
      "Use 'if-else' blocks to check answers",
      "Create a score variable that increases for correct answers",
      "Show feedback (correct/wrong) after each question",
      "Display the final score at the end",
      "Add sound effects for correct and wrong answers",
      "Customize the background for each question"
    ],
    expectedOutput: "A working quiz with 5+ questions, score tracking, feedback messages, and sound effects.",
    maxMarks: 80,
    difficultyLevel: "Medium",
    estimatedTime: "1.5 hours",
    referenceResources: [],
  },
  // MS Paint
  {
    id: "paint-drawing",
    title: "My Dream House Drawing",
    description: "Use MS Paint tools to draw a colorful picture of your dream house with a garden, trees, and sky.",
    technology: "MS Paint",
    submissionType: "Screenshot",
    learningObjective: "Learn to use drawing tools, shapes, fill colors, and text tool in MS Paint.",
    instructions: [
      "Open MS Paint and set canvas size to 800x600",
      "Draw the house structure using the Rectangle tool",
      "Add a triangular roof using the Line tool",
      "Draw windows and a door using shapes",
      "Add a garden with flowers using the Brush tool",
      "Draw trees using circles and lines",
      "Fill the sky with light blue color using Fill tool",
      "Add the sun and clouds",
      "Write your name using the Text tool",
      "Save the file as PNG"
    ],
    expectedOutput: "A colorful drawing of a dream house with garden, trees, sky, sun, clouds, and your name.",
    maxMarks: 50,
    difficultyLevel: "Easy",
    estimatedTime: "45 minutes",
    referenceResources: [],
  },
  // MS Word
  {
    id: "word-newsletter",
    title: "School Newsletter",
    description: "Create a one-page school newsletter in MS Word using formatting, columns, images, and text styling.",
    technology: "MS Word",
    submissionType: "File Upload",
    learningObjective: "Learn page layout, text formatting, inserting images, using columns, and headers/footers in MS Word.",
    instructions: [
      "Open MS Word and set page orientation to Portrait",
      "Add a header with the newsletter title in bold, large font",
      "Create a 2-column layout for the main content",
      "Write at least 3 short articles (school events, sports, achievements)",
      "Insert at least 2 relevant images from clipart",
      "Add a watermark saying 'School Newsletter'",
      "Format text with different fonts, sizes, and colors",
      "Add page borders for decoration",
      "Include a footer with page number and date",
      "Save as .docx file"
    ],
    expectedOutput: "A professionally formatted one-page newsletter with columns, images, watermark, and proper formatting.",
    maxMarks: 80,
    difficultyLevel: "Medium",
    estimatedTime: "1.5 hours",
    referenceResources: [],
  },
  {
    id: "word-resume",
    title: "My First Resume",
    description: "Create a simple resume/bio-data document in MS Word with proper formatting and sections.",
    technology: "MS Word",
    submissionType: "File Upload",
    learningObjective: "Learn document formatting, tables, bullet points, and professional document design in MS Word.",
    instructions: [
      "Open MS Word and set margins to Normal",
      "Add your name as a heading in large bold font",
      "Add sections: About Me, Education, Skills, Hobbies",
      "Use bullet points for listing skills and hobbies",
      "Insert a table for your education details",
      "Add a photo placeholder using a shape",
      "Apply consistent formatting throughout",
      "Add horizontal lines between sections",
      "Save as .docx file"
    ],
    expectedOutput: "A clean, well-formatted resume with all required sections, consistent styling, and proper layout.",
    maxMarks: 60,
    difficultyLevel: "Easy",
    estimatedTime: "1 hour",
    referenceResources: [],
  },
  // MS PowerPoint
  {
    id: "ppt-presentation",
    title: "Planet Earth Presentation",
    description: "Create a 10-slide PowerPoint presentation about Planet Earth with animations, transitions, and media.",
    technology: "MS PowerPoint",
    submissionType: "File Upload",
    learningObjective: "Learn to create presentations with slides, animations, transitions, images, and proper slide design.",
    instructions: [
      "Open PowerPoint and choose a theme",
      "Slide 1: Title slide with 'Planet Earth' and your name",
      "Slide 2-3: Earth's structure with diagrams",
      "Slide 4-5: Continents and oceans with a world map",
      "Slide 6-7: Climate and weather patterns",
      "Slide 8: Endangered species with images",
      "Slide 9: How to protect our planet",
      "Slide 10: Thank You slide with references",
      "Add entrance animations to text and images",
      "Add slide transitions between all slides",
      "Insert at least 5 relevant images",
      "Save as .pptx file"
    ],
    expectedOutput: "A 10-slide presentation with consistent theme, animations, transitions, images, and informative content.",
    maxMarks: 100,
    difficultyLevel: "Medium",
    estimatedTime: "2 hours",
    referenceResources: [],
  },
  // MS Excel
  {
    id: "excel-marksheet",
    title: "Class Marksheet Calculator",
    description: "Create a marksheet in MS Excel with student names, marks in 5 subjects, total, percentage, and grade using formulas.",
    technology: "MS Excel",
    submissionType: "File Upload",
    learningObjective: "Learn to use Excel formulas (SUM, AVERAGE, IF), formatting, and conditional formatting for data analysis.",
    instructions: [
      "Open Excel and create column headers: Roll No, Name, English, Math, Science, Social, Computer",
      "Enter data for at least 10 students",
      "Add a Total column using SUM formula",
      "Add a Percentage column (Total/500 * 100)",
      "Add an Average column using AVERAGE formula",
      "Add a Grade column using nested IF formula",
      "Apply formatting: bold headers, borders, center alignment",
      "Add conditional formatting for Pass/Fail (below 33% = red)",
      "Create a bar chart showing subject-wise average marks",
      "Add a title row and format the sheet professionally"
    ],
    expectedOutput: "A complete marksheet with formulas for total, percentage, average, grades, conditional formatting, and a chart.",
    maxMarks: 100,
    difficultyLevel: "Medium",
    estimatedTime: "2 hours",
    referenceResources: [],
  },
  {
    id: "excel-budget",
    title: "Monthly Budget Tracker",
    description: "Create a personal monthly budget tracker in Excel with categories, expenses, income, and charts.",
    technology: "MS Excel",
    submissionType: "File Upload",
    learningObjective: "Learn data organization, SUM formulas, cell formatting, and chart creation in MS Excel.",
    instructions: [
      "Create headers: Category, Budget, Actual, Difference",
      "Add expense categories: Food, Transport, Books, Entertainment, Savings",
      "Enter budget amounts and actual spending",
      "Use formulas to calculate difference (Budget - Actual)",
      "Add a Total row using SUM",
      "Create a pie chart showing expense distribution",
      "Add conditional formatting: green if under budget, red if over",
      "Format currency values properly",
      "Save the workbook"
    ],
    expectedOutput: "A budget tracker with categories, formulas, conditional formatting, and a pie chart.",
    maxMarks: 80,
    difficultyLevel: "Easy",
    estimatedTime: "1.5 hours",
    referenceResources: [],
  },
  // HTML/CSS
  {
    id: "html-portfolio",
    title: "My Personal Webpage",
    description: "Create a personal webpage using HTML and CSS with sections about yourself, hobbies, and a photo gallery.",
    technology: "HTML/CSS",
    submissionType: "Code",
    learningObjective: "Learn HTML structure, semantic tags, CSS styling, and basic layout design for web pages.",
    instructions: [
      "Create an index.html file with proper HTML5 structure",
      "Add a header section with your name and navigation links",
      "Create an About Me section with a paragraph about yourself",
      "Add a Hobbies section with an unordered list",
      "Create a photo gallery section with at least 4 images",
      "Add a Contact section with your email (can be fake)",
      "Create a styles.css file and link it",
      "Style the page with colors, fonts, and spacing",
      "Make the navigation links work (use anchor tags)",
      "Add a footer with copyright text"
    ],
    expectedOutput: "A complete webpage with header, about me, hobbies list, photo gallery, contact section, and CSS styling.",
    maxMarks: 100,
    difficultyLevel: "Medium",
    estimatedTime: "2.5 hours",
    referenceResources: [],
  },
  {
    id: "html-table",
    title: "HTML Timetable Page",
    description: "Create a school timetable webpage using HTML tables with proper formatting and CSS colors.",
    technology: "HTML/CSS",
    submissionType: "Code",
    learningObjective: "Learn HTML table structure, cell merging, borders, and CSS table styling.",
    instructions: [
      "Create an HTML file with a proper structure",
      "Add a heading: 'My Weekly Timetable'",
      "Create a table with days as columns (Mon-Sat)",
      "Add rows for each period (Period 1-8)",
      "Fill in subject names for each cell",
      "Use colspan for lunch break row",
      "Add CSS to style the table with borders and colors",
      "Color-code different subjects",
      "Add hover effect on table rows",
      "Save and test in a browser"
    ],
    expectedOutput: "A styled school timetable webpage with colored cells, proper borders, and hover effects.",
    maxMarks: 60,
    difficultyLevel: "Easy",
    estimatedTime: "1 hour",
    referenceResources: [],
  },
  // Python
  {
    id: "python-calculator",
    title: "Python Calculator Program",
    description: "Build a calculator program in Python that performs basic arithmetic operations with a menu-driven interface.",
    technology: "Python",
    submissionType: "Code",
    learningObjective: "Learn Python basics including variables, user input, functions, conditional statements, and loops.",
    instructions: [
      "Create a new Python file called calculator.py",
      "Display a menu: 1. Add, 2. Subtract, 3. Multiply, 4. Divide, 5. Exit",
      "Take user input for menu choice",
      "Take two numbers as input from the user",
      "Create separate functions for each operation",
      "Handle division by zero with an error message",
      "Use a while loop to repeat until user chooses Exit",
      "Display results with proper formatting",
      "Test with various inputs including edge cases"
    ],
    expectedOutput: "A working calculator with menu, all 4 operations, error handling, and loop-based repetition.",
    maxMarks: 80,
    difficultyLevel: "Medium",
    estimatedTime: "1.5 hours",
    referenceResources: [],
  },
  {
    id: "python-quiz-game",
    title: "Python Quiz Game",
    description: "Create a text-based quiz game in Python with questions, scoring, and a final result display.",
    technology: "Python",
    submissionType: "Code",
    learningObjective: "Learn lists, dictionaries, loops, conditionals, and string formatting in Python.",
    instructions: [
      "Create a list of at least 10 quiz questions",
      "Store questions and correct answers in a dictionary",
      "Display questions one by one using a loop",
      "Take user input for each answer",
      "Compare answers and track the score",
      "Display correct/incorrect feedback after each question",
      "Show the final score and percentage at the end",
      "Add a grade system (A, B, C, D, F)",
      "Handle invalid inputs gracefully"
    ],
    expectedOutput: "A working quiz game with 10+ questions, score tracking, feedback, and final grade display.",
    maxMarks: 80,
    difficultyLevel: "Medium",
    estimatedTime: "1.5 hours",
    referenceResources: [],
  },
  // GIMP
  {
    id: "gimp-poster",
    title: "Event Poster Design",
    description: "Design a colorful event poster using GIMP with text, images, effects, and proper layout.",
    technology: "GIMP",
    submissionType: "Screenshot",
    learningObjective: "Learn image editing basics including layers, text tool, filters, and color manipulation in GIMP.",
    instructions: [
      "Open GIMP and create a new image (A4 size, 300 DPI)",
      "Add a gradient background using the Gradient tool",
      "Insert a title text with large, bold font",
      "Add event details: date, time, venue using Text tool",
      "Import and place at least 2 relevant images",
      "Use layers to organize different elements",
      "Apply at least one filter effect (blur, sharpen, etc.)",
      "Add decorative elements like borders or shapes",
      "Export the poster as PNG",
      "Save the GIMP project file (.xcf)"
    ],
    expectedOutput: "A professional-looking event poster with gradient background, text, images, effects, and proper layout.",
    maxMarks: 80,
    difficultyLevel: "Medium",
    estimatedTime: "2 hours",
    referenceResources: [],
  },
  // KRITA
  {
    id: "krita-digital-art",
    title: "Digital Art Creation",
    description: "Create a digital art piece using KRITA with different brushes, layers, and color techniques.",
    technology: "KRITA",
    submissionType: "Screenshot",
    learningObjective: "Learn digital art fundamentals including brush types, layers, blending modes, and color theory in KRITA.",
    instructions: [
      "Open KRITA and create a new canvas (1920x1080)",
      "Create a rough sketch layer for your artwork",
      "Add a new layer for clean line art",
      "Create separate layers for base colors",
      "Use different brush types for textures",
      "Add shading and highlights on separate layers",
      "Experiment with blending modes",
      "Add a background layer",
      "Export as PNG",
      "Save the KRITA project file (.kra)"
    ],
    expectedOutput: "A complete digital artwork with proper layers, coloring, shading, and background.",
    maxMarks: 80,
    difficultyLevel: "Medium",
    estimatedTime: "2 hours",
    referenceResources: [],
  },
  // Canva
  {
    id: "canva-social-media",
    title: "Social Media Post Design",
    description: "Design a set of 3 social media posts for a school event using Canva with consistent branding.",
    technology: "Canva",
    submissionType: "Screenshot",
    learningObjective: "Learn graphic design principles, color consistency, typography, and layout design using Canva.",
    instructions: [
      "Open Canva and choose Instagram Post template",
      "Design Post 1: Event announcement with date and title",
      "Design Post 2: Event details and schedule",
      "Design Post 3: Registration/call-to-action post",
      "Use a consistent color palette across all 3 posts",
      "Use the same font family for branding consistency",
      "Add relevant images or illustrations from Canva library",
      "Include the school logo/name on each post",
      "Download all 3 posts as PNG",
      "Take screenshots showing the design process"
    ],
    expectedOutput: "3 consistent social media posts with matching branding, colors, fonts, and professional layout.",
    maxMarks: 80,
    difficultyLevel: "Easy",
    estimatedTime: "1.5 hours",
    referenceResources: [],
  },
  // MIT App Inventor
  {
    id: "appinventor-app",
    title: "Simple Calculator App",
    description: "Build a basic calculator mobile app using MIT App Inventor with a user interface and arithmetic operations.",
    technology: "MIT App Inventor",
    submissionType: "Screenshot",
    learningObjective: "Learn app development basics including UI design, event handling, and logic blocks in MIT App Inventor.",
    instructions: [
      "Open MIT App Inventor and create a new project",
      "Design the UI: add TextBox for display, buttons for digits 0-9",
      "Add operation buttons: +, -, ×, ÷, =, Clear",
      "Use HorizontalArrangement for button rows",
      "In Blocks editor, create variables for operands",
      "Program digit buttons to update the display",
      "Program operation buttons to store the operation",
      "Program the = button to calculate and show result",
      "Program Clear button to reset everything",
      "Test the app using the emulator or phone",
      "Take screenshots of both Designer and Blocks views"
    ],
    expectedOutput: "A working calculator app with all 4 operations, clean UI, and proper functionality.",
    maxMarks: 100,
    difficultyLevel: "Hard",
    estimatedTime: "2.5 hours",
    referenceResources: [],
  },
  // MS Access
  {
    id: "access-database",
    title: "Student Records Database",
    description: "Create a student records database in MS Access with tables, forms, queries, and reports.",
    technology: "MS Access",
    submissionType: "Screenshot",
    learningObjective: "Learn database concepts including tables, relationships, forms, queries, and reports in MS Access.",
    instructions: [
      "Open MS Access and create a new blank database",
      "Create a Students table with fields: ID, Name, Class, Section, Roll No, Contact",
      "Set appropriate data types for each field",
      "Set ID as the primary key with AutoNumber",
      "Enter at least 10 student records",
      "Create a form for easy data entry",
      "Create a query to filter students by class",
      "Create a report showing all students sorted by class",
      "Take screenshots of table, form, query, and report",
      "Save the database file"
    ],
    expectedOutput: "A database with student table, data entry form, filter query, and a formatted report.",
    maxMarks: 100,
    difficultyLevel: "Hard",
    estimatedTime: "2 hours",
    referenceResources: [],
  },
];

export const getTemplatesForTechnology = (tech: string): ProjectTemplate[] => {
  return PROJECT_TEMPLATES.filter(t => t.technology === tech);
};
